import "~/styles/globals.css";

import { Press_Start_2P } from "next/font/google";
import { type Metadata } from "next";
import localFont from "next/font/local";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";

const pressStart = Press_Start_2P({
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});

const ka = localFont({
  src: "../../public/fonts/ka1.ttf",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${ka.className}`}>
      <body>
        <SessionProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
